movie_app/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('movies/', views.show_all_movie, name='movies'),
    path('movie/<slug:slug_movie>/', views.show_one_movie, name='movie-detail'),
    path('serials/', views.show_all_serial, name='serials'),
    path('serial/<slug:slug_serial>/', views.show_one_serial, name='serial-detail'),
    path('actors/', views.show_actors, name='all_actors'),
    path('actor/<slug:slug_name>/', views.show_actor, name='actor_film'),
    ]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
# from movie_app_api import views
from movie_project import settings
from django.contrib.sitemaps.views import sitemap
from movie_app.sitemaps import MovieSitemap
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView # new


# from rest_framework import routers


admin.site.index_title = "Админ панель Django"

sitemaps = {
    "movies": MovieSitemap,
}

# router = routers.SimpleRouter()
# router.register(r'', views.MovieViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie_app.urls", namespace="index")),
    path("video/", include("video_player.urls", namespace="video_player")),
    path("user/", include("user.urls", namespace="user")),
    # debug
    path("__debug__/", include("debug_toolbar.urls")),
    # social auth
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    # sitemap
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
    # авторизация по токенам JWT
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
    # авторизация по токенам
    path("api/v1/drf-auth", include("rest_framework.urls")),
    path("api/v1/auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
    # API версия 1
    path("api/v1/", include("movie_app_api.urls")),
    # schema
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    #router
    # path("api/v1/", include(router.urls)), # for router
    # path("api/v2/", include("movie_app_api_v2.urls")), # API версия 2
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
]

video_player/urls.py
from django.urls import path
from . import views

app_name = "video_player"

urlpatterns = [
    path('film/<slug:slug_film>/watch/', views.film_player, name='film_player'),
    path('stream/film/<slug:slug_film>/<str:quality>/', views.stream_video, name='stream_video'),
    path('serial/<slug:slug_serial>/season/<int:season_number>/episode/<int:episode_number>/watch/', views.episode_player, name='episode_player'),
    path('stream/serial/<slug:slug_serial>/season/<int:season_number>/episode/<int:episode_number>/<str:quality>/', views.stream_serial, name='stream_serial'),
]

movie_app/models.py
from django.db import models
from django.urls import reverse

class Director(models.Model):
    first_name = models.CharField(max_length=100, verbose_name="Имя")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия")
    email = models.EmailField(verbose_name="Почта")
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True, verbose_name="URL")

    class Meta:
        db_table = "derictor"
        verbose_name = "Режисер"
        verbose_name_plural = "Режисеры"

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"


class Actor(models.Model):

    MALE = "M"
    FEMALE = "F"

    GENDERS = [
        (MALE, "мужчина"),
        (FEMALE, "женщина")
    ]

    first_name = models.CharField(max_length=100, verbose_name="Имя")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия")
    gender = models.CharField(max_length=1, choices=GENDERS, default=MALE, verbose_name="Гендер")
    image = models.ImageField(upload_to="static/images/actors", blank=True, null=True, default="static/images/not_image.jpeg",)
    slug = models.SlugField(max_length=100, blank=True, null=True, verbose_name="URL")
    age = models.PositiveIntegerField(blank=True, null=True, verbose_name="Возвраст")
    country = models.CharField(max_length=100, blank=True, null=True, verbose_name="Место рождения")
    description = models.TextField(max_length=500, blank=True, null=True, verbose_name="Биография")

    class Meta:
        db_table = "actor"
        verbose_name = "Актера"
        verbose_name_plural = "Актеры"

    def __str__(self):
        if self.gender == self.MALE:
            return f"Актер {self.first_name} {self.last_name}"
        return f"Актриса {self.first_name} {self.last_name}"


class Movie(models.Model):

    EURO = "EUR"
    RUB = "RUB"
    POUND = "PND"
    USD = "USD"

    CURRENCY_CHOICES = [
        (EURO, "Euro"),
        (RUB, "Ruble"),
        (POUND, "Pound"),
        (USD, "Dollar"),
    ]

    NEWRELEASES = "NEWRELEASES"
    POPULAR = "POPULAR"
    CLASSICS = "CLASSICS"
    COMMON = "COMMON"

    CATEGORY_CHOICES = [
        (NEWRELEASES, "new_releases"),
        (POPULAR, "popular"),
        (CLASSICS, "classics"),
        (COMMON, "common"),
    ]

    name = models.CharField(max_length=40, verbose_name="Название")
    rating = models.FloatField(null=True, blank=True, verbose_name="Рейтинг")
    rating_imdb = models.FloatField(null=True, blank=True, verbose_name="Рейтинг IMDb")
    year = models.IntegerField(null=True, blank=True, verbose_name="Год")
    budget = models.IntegerField(default=100000, verbose_name="Бюджет")
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name="Описание")
    slug = models.SlugField(default="", max_length=200, unique=True, null=False, verbose_name="URL")
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=USD)
    director = models.ForeignKey(Director, on_delete=models.PROTECT, blank=True, null=True, related_name="movies", verbose_name="Режисер")
    actor = models.ManyToManyField(Actor, related_name="movies", verbose_name="Актер")
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=COMMON, verbose_name="Категория для главной")
    category_film = models.CharField(max_length=100, unique=False, blank=True, null=True, verbose_name="Категория фильма")
    age = models.PositiveIntegerField(blank=True, null=True, verbose_name="Возврастное ограничение")
    time = models.FloatField(blank=True, null=True, verbose_name="Время просмотра")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    image = models.ImageField(upload_to="movies", blank=True, null=True, verbose_name="Изображение")
    image_back = models.ImageField(upload_to="movies_back", blank=True, null=True, verbose_name="Фон")
    video_medium = models.FileField(upload_to='videos/480', blank=True, null=True, verbose_name="Видео 480")
    video_high = models.FileField(upload_to='videos/720', blank=True, null=True, verbose_name="Видео 720")
    video_hd = models.FileField(upload_to='videos/1080', blank=True, null=True, verbose_name="Видео 1080")

    class Meta:
        db_table = "movie"
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"

    def __str__(self):
        return f"{self.name} - {self.rating}"

    def get_video_sources(self):
        sources = []
        if self.video_medium:
            sources.append('480p')
        if self.video_high:
            sources.append('720p')
        if self.video_hd:
            sources.append('1080p')
        return sources
    
    def get_absolute_url(self):
        return reverse('index:movie-detail',
                       args=[self.slug])

class Serial(models.Model):
    NEWRELEASES = "NEWRELEASES"
    POPULAR = "POPULAR"
    CLASSICS = "CLASSICS"
    COMMON = "COMMON"

    CATEGORY_CHOICES = [
        (NEWRELEASES, "new_releases"),
        (POPULAR, "popular"),
        (CLASSICS, "classics"),
        (COMMON, "common"),
    ]

    EURO = "EUR"
    RUB = "RUB"
    POUND = "PND"
    USD = "USD"

    CURRENCY_CHOICES = [
        (EURO, "Euro"),
        (RUB, "Ruble"),
        (POUND, "Pound"),
        (USD, "Dollar"),
    ]

    name = models.CharField(max_length=40, verbose_name="Название")
    rating = models.FloatField(null=True, blank=True, verbose_name="Рейтинг")
    rating_imdb = models.FloatField(null=True, blank=True, verbose_name="Рейтинг IMDb")
    year = models.IntegerField(null=True, blank=True, verbose_name="Год")
    budget = models.IntegerField(default=100000, verbose_name="Бюджет")
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name="Описание")
    slug = models.SlugField(default="", max_length=200, unique=True, null=False, verbose_name="URL")
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=USD, verbose_name="Валюта")
    director = models.ForeignKey('Director', on_delete=models.PROTECT, blank=True, null=True, related_name="serials", verbose_name="Режиссер")
    actors = models.ManyToManyField('Actor', related_name="serials", verbose_name="Актеры")
    category_serial = models.CharField(max_length=100, choices=CATEGORY_CHOICES, default=COMMON, blank=True, null=True, verbose_name="Категория сериала")
    age = models.PositiveIntegerField(blank=True, null=True, verbose_name="Возрастное ограничение")
    time = models.FloatField(blank=True, null=True, verbose_name="Время просмотра")
    image = models.ImageField(upload_to="serials", blank=True, null=True, verbose_name="Изображение")
    image_back = models.ImageField(upload_to="serial_back", blank=True, null=True, verbose_name="Фон")

    class Meta:
        db_table = "serial"
        verbose_name = "Сериал"
        verbose_name_plural = "Сериалы"

    def __str__(self):
        return f"{self.name} - {self.rating}"
    
class Episode(models.Model):
    serial = models.ForeignKey(Serial, on_delete=models.CASCADE, related_name='episodes', verbose_name="Сериал")
    slug = models.SlugField(default="", max_length=200, unique=True, null=False, verbose_name="URL")
    season_number = models.PositiveIntegerField(verbose_name="Номер сезона")
    episode_number = models.PositiveIntegerField(verbose_name="Номер серии")
    name = models.CharField(max_length=100, verbose_name="Название серии")
    image = models.ImageField(upload_to="episodes", blank=True, null=True, verbose_name="Изображение")
    video_medium = models.FileField(upload_to='videos/serials/480', blank=True, null=True, verbose_name="Видео 480p")
    video_high = models.FileField(upload_to='videos/serials/720', blank=True, null=True, verbose_name="Видео 720p")
    video_hd = models.FileField(upload_to='videos/serials/1080', blank=True, null=True, verbose_name="Видео 1080p")

    class Meta:
        db_table = "episode"
        verbose_name = "Серия"
        verbose_name_plural = "Серии"
        unique_together = ['serial', 'season_number', 'episode_number']

    def __str__(self):
        return f"Сериал: {self.serial.name}, Сезон: {self.season_number}, Серия: {self.episode_number}"

    def get_video_sources(self):
        sources = []
        if self.video_medium:
            sources.append('480p')
        if self.video_high:
            sources.append('720p')
        if self.video_hd:
            sources.append('1080p')
        return sources

movie_app/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import F
from movie_app.utils import q_search
from .models import Movie, Director, Actor, Serial



def index(request):

    movies = Movie.objects.all()
    movies_slider = Movie.objects.all().order_by(
        "-rating", "-rating_imdb"
    )[:7]

    context = {"movies": movies, "slider": movies_slider}

    return render(request, "movie_app/index.html", context=context)

def search(request):
    query = request.GET.get('q')
    results = q_search(query)

    context = {
        'query': query,
        'results': results,
    }
    return render(request, 'movie_app/search_results.html', context)

def show_all_movie(request):

    movies = Movie.objects.order_by(
            F("rating").desc(nulls_last=True), F("name").asc(nulls_last=True), "-budget"
        )

    context = {
        "movies": movies
    }
    return render(request, "movie_app/all_movies.html", context=context)


def show_one_movie(request, slug_movie):
    movie = get_object_or_404(Movie, slug=slug_movie)

    context = {"movie": movie}

    return render(request, "movie_app/film.html", context=context)


def show_all_serial(request):
        
    serials = Serial.objects.order_by(
            F("rating").desc(nulls_last=True), F("name").asc(nulls_last=True), "-budget"
        )

    context = {
        "serials": serials,
        }
    return render(request, "movie_app/all_serials.html", context=context)


def show_one_serial(request, slug_serial):
    serial = get_object_or_404(Serial, slug=slug_serial)
    episodes = serial.episodes.all().order_by('pk')
    context = {"serial": serial, "episodes": episodes}

    return render(request, "movie_app/serial.html", context=context)


def show_directors(request):
    director = Director.objects.order_by("first_name")

    context = {"directors": director}

    return render(request, "movie_app/directors.html", context=context)


def show_one_director(request, slug_director):
    director = get_object_or_404(Director, slug=slug_director)

    context = {"director": director}

    return render(request, "movie_app/one_director.html", context=context)


def show_actors(request):

    actors = Actor.objects.all()

    context = {"actors": actors}

    return render(request, "movie_app/actors.html", context=context)


def show_actor(request, slug_name):
    actor = get_object_or_404(Actor, slug=slug_name)

    context = {"actor": actor}

    return render(request, "movie_app/one_actor.html", context=context)

movie_app/templates/movie_app/actors.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Actors Grid</title>
{% endblock  %}

{% block css %}
<link rel="stylesheet" href="{% static "css/actors.css" %}"> <!-- Путь к вашему CSS файлу -->
{% endblock  %}

{% block content %}
<div class="navigation">
    <button>All Actors</button>
    <button>About Us</button>
    <button>Contact</button>
    <!-- Добавьте другие кнопки по аналогии -->
</div>
<div class="grid-container">
    {% for actor in actors %}
        <div class="grid-item">
            <img src="{{ actor.image.url }}" alt="{{actor.first_name}}">
            <p><a href="{% url "index:actor_film" actor.slug %}" class="black-link">{{actor}}</a></p>
        </div>
    {% endfor %}
</div>
{% endblock  %}

movie_app/templates/movie_app/all_serials.html
{% extends 'base.html' %}
{% load static %}
{% load split_filter %}

{% block title %}
<title>Serials</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/card_movie.css' %}">
<link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/panel/panel.css' %}">
{% endblock  %}

{% block content %}
{% include "includes/panel.html" %}

<div class="count-movie">
    <h1>Сериалы {{serials|length}}</h1>
</div>

<div class="content">
    <div class="movie-grid">
        {% for serial in serials %}
        <a href="{% url "index:serial-detail" serial.slug %}">
            <div class="movie-card">
                    {% if serial.image %}
                        <img src="{{serial.image.url}}" alt="{{serial.name}}">
                    {% else %}
                        <img src="{% static 'images/not_image.jpeg' %}" alt="...">
                    {% endif %}
                <div class="movie-info">
                    <h3>{{serial.name}}</h3>
                    <div class="movie-card-rating-container">
                        <div class="movie-card-rating kinopoisk">
                            <span class="source">Кинопоиск</span> {{ serial.rating }}
                        </div>
                        <div class="movie-card-rating imdb">
                            <span class="source">IMDb</span> {{ serial.rating_imdb }}
                        </div>
                    </div>
                    <div class="movie-card-details-container">
                        <div class="movie-card-detail">
                            <i class="fas fa-clock"></i>
                            <span>{{ serial.time|split:"."|first }}ч {{ serial.time|split:"."|last }}м</span>
                        </div>
                        <div class="movie-card-detail">
                            <i class="fas fa-calendar-alt"></i>
                            <span>{{ serial.year }}</span>
                        </div>
                        <div class="movie-card-detail">
                            <i class="fas fa-film"></i>
                            <span>{{ serial.category_serial }}</span>
                        </div>
                        <div class="movie-card-detail">
                            <i class="fas fa-exclamation-circle"></i>
                            <span>{{ serial.age }}+</span>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% include "includes/footer.html" %}
{% endblock %}

movie_app/templates/movie_app/film.html
{% extends "base.html" %}
{% load static %}
{% load split_filter %}

{% block title %}
<title>{{ movie.name }} - Movie Flow</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/film.css' %}">
<link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/panel/panel.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block content %}
{% include "includes/panel.html" %}
<div class="movie-view-container" style="background-image: url('{{ movie.image_back.url }}');">
    <div class="slide-content">
        <h2>{{ movie.name }}</h2>
        <p>{{ movie.description }}</p>
        <div class="movie-info">
            <div class="rating-container">
                <div class="rating kinopoisk">
                    <span class="source">Кинопоиск</span> {{ movie.rating }}
                </div>
                <div class="rating imdb">
                    <span class="source">IMDb</span> {{ movie.rating_imdb }}
                </div>
            </div>
            <div class="movie-details-container">
                <div class="movie-detail">
                    <i class="fas fa-clock"></i>
                    <span>{{ movie.time|split:"."|first }}ч {{ movie.time|split:"."|last }}м</span>
                </div>
                <div class="movie-detail">
                    <i class="fas fa-calendar-alt"></i>
                    <span>{{ movie.year }}</span>
                </div>
                <div class="movie-detail">
                    <i class="fas fa-film"></i>
                    <span>{{ movie.category_film }}</span>
                </div>
                <div class="movie-detail">
                    <i class="fas fa-exclamation-circle"></i>
                    <span>{{ movie.age }}+</span>
                </div>
                <div class="movie-actions">
                    <a href="{% url 'video_player:film_player' movie.slug %}" class="watch-button">Смотреть фильм</a>
                    <a href="#" class="add-to-favorites-button">Добавить в избранное</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% include "includes/footer.html" %}
{% endblock %}

movie_app/templates/movie_app/one_actor.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/actor.css" %}">
    <title>Actor Profile</title>
</head>
<body>
    <div class="container">
        <div class="actor-info">
            <img src="{{ actor.image.url }}" alt="Actor Photo">
            <div>
                <h2>{{ actor }}</h2>
                <p>Age: {{actor.age}}</p>
                <p>Country: {{actor.country}}</p>
                <p>Biography: {{actor.description}}</p>
            </div>
        </div>
    </div>
</body>
</html>

movie_app/templates/movie_app/search_results.html
{% extends 'base.html' %}
{% load static %}
{% load split_filter %}

{% block title %}
<title>All Movies {{movies|length}}</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/card_movie.css' %}">
<link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/panel/panel.css' %}">
<link rel="stylesheet" href="{% static 'css/results.css' %}">
{% endblock  %}

{% block content %}
{% include "includes/panel.html" %}
<div class="content">
    {% if results %}
        <div class="search-results">
            <h1>Результаты по запросу</h1>
        </div>
    {% else %}
        <div class="search-error">
            <h1>Что-то пошло не так!</h1>
            <p>По вашему запросу ничего не найдено.</p>
        </div>
    {% endif %}

    <div class="movie-grid">
        {% for result in results %}
            <div class="movie-card">
                {% if result.type == 'movie' %}
                    <a href="{% url 'index:movie-detail' result.object.slug %}">
                        {% if result.object.image %}
                            <img src="{{result.object.image.url}}" alt="{{result.object.name}}">
                        {% else %}
                            <img src="{% static 'images/not_image.jpeg' %}" alt="...">
                        {% endif %}
                        <div class="movie-info">
                                <h3>{{result.object.name}}</h3>
                                <div class="movie-card-rating-container">
                                    <div class="movie-card-rating kinopoisk">
                                        <span class="source">Кинопоиск</span> {{ result.object.rating }}
                                    </div>
                                    <div class="movie-card-rating imdb">
                                        <span class="source">IMDb</span> {{ result.object.rating_imdb }}
                                    </div>
                                </div>
                                <div class="movie-card-details-container">
                                    <div class="movie-card-detail">
                                        <i class="fas fa-clock"></i>
                                        <span>{{ result.object.time|split:"."|first }}ч {{ result.object.time|split:"."|last }}м</span>
                                    </div>
                                    <div class="movie-card-detail">
                                        <i class="fas fa-calendar-alt"></i>
                                        <span>{{ result.object.year }}</span>
                                    </div>
                                    <div class="movie-card-detail">
                                        <i class="fas fa-film"></i>
                                        <span>{{ result.object.category_film }}</span>
                                    </div>
                                    <div class="movie-card-detail">
                                        <i class="fas fa-exclamation-circle"></i>
                                        <span>{{ result.object.age }}+</span>
                                    </div>
                                </div>
                        </div>
                    </a>
                {% elif result.type == 'serial' %}
                    <a href="{% url 'index:serial-detail' result.object.slug %}">
                        {% if result.object.image %}
                            <img src="{{result.object.image.url}}" alt="{{movie.name}}">
                        {% else %}
                            <img src="{% static 'images/not_image.jpeg' %}" alt="...">
                        {% endif %}
                        <div class="movie-info">
                                <h3>{{result.object.name}}</h3>
                                <div class="movie-card-rating-container">
                                    <div class="movie-card-rating kinopoisk">
                                        <span class="source">Кинопоиск</span> {{ result.object.rating }}
                                    </div>
                                    <div class="movie-card-rating imdb">
                                        <span class="source">IMDb</span> {{ result.object.rating_imdb }}
                                    </div>
                                </div>
                                <div class="movie-card-details-container">
                                    <div class="movie-card-detail">
                                        <i class="fas fa-clock"></i>
                                        <span>{{ result.object.time|split:"."|first }}ч {{ result.object.time|split:"."|last }}м</span>
                                    </div>
                                    <div class="movie-card-detail">
                                        <i class="fas fa-calendar-alt"></i>
                                        <span>{{ result.object.year }}</span>
                                    </div>
                                    <div class="movie-card-detail">
                                        <i class="fas fa-film"></i>
                                        <span>{{ result.object.category_film }}</span>
                                    </div>
                                    <div class="movie-card-detail">
                                        <i class="fas fa-exclamation-circle"></i>
                                        <span>{{ result.object.age }}+</span>
                                    </div>
                                </div>
                        </div>
                    </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>
{% include "includes/footer.html" %}
{% endblock %}

movie_app/templates/movie_app/serial.html
{% extends "base.html" %}
{% load static %}
{% load split_filter %}

{% block title %}
<title>{{ serial.name }} - Movie Flow</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/film.css' %}">
<link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/panel/panel.css' %}">
<link rel="stylesheet" href="{% static 'css/carousel.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block content %}
{% include "includes/panel.html" %}
<div class="movie-view-container" style="background-image: url('{{ serial.image_back.url }}');">
    <div class="slide-content">
        <h2>{{ serial.name }}</h2>
        <p>{{ serial.description }}</p>
        <div class="movie-info">
            <div class="rating-container">
                <div class="rating kinopoisk">
                    <span class="source">Кинопоиск</span> {{ serial.rating }}
                </div>
                <div class="rating imdb">
                    <span class="source">IMDb</span> {{ serial.rating_imdb }}
                </div>
            </div>
            <div class="movie-details-container">
                <div class="movie-detail">
                    <i class="fas fa-clock"></i>
                    <span>{{ serial.time|split:"."|first }}ч {{ serial.time|split:"."|last }}м</span>
                </div>
                <div class="movie-detail">
                    <i class="fas fa-calendar-alt"></i>
                    <span>{{ serial.year }}</span>
                </div>
                <div class="movie-detail">
                    <i class="fas fa-film"></i>
                    <span>{{ serial.category_serial }}</span>
                </div>
                <div class="movie-detail">
                    <i class="fas fa-exclamation-circle"></i>
                    <span>{{ serial.age }}+</span>
                </div>
                <div class="movie-actions">
                    <a href="{% url 'video_player:episode_player' serial.slug 1 1 %}" class="watch-button">Смотреть сериал</a>
                    <a href="#" class="add-to-favorites-button">Добавить в избранное</a>
                </div>
            </div>
        </div>

        <!-- Carousel Start -->
        <div class="carousel">
            <button class="prev" onclick="moveCarousel(-1)">&#10094;</button>
            <div class="carousel-container">
                <div class="carousel-track">
                    {% for episode in episodes %}
                        <div class="carousel-item">
                            <a href="{% url 'video_player:episode_player' serial.slug episode.season_number episode.episode_number %}">
                                {% if episode.image %}
                                    <img src="{{ episode.image.url }}" alt="{{ episode.name }}">
                                {% else %}
                                    <img src="{% static 'images/not_image.jpeg' %}" alt="No image available">
                                {% endif %}
                                <div class="carousel-text">{{ episode.name|truncatechars:10 }} Серия {{ episode.episode_number }}, Сезон {{ episode.season_number }}</div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <button class="next" onclick="moveCarousel(1)">&#10095;</button>
        </div>
        <!-- Carousel End -->

    </div>
</div>
{% include "includes/footer.html" %}
{% endblock %}

{% block javascript %}
<script src="{% static "js/carousel/carousel.js" %}"></script>
{% endblock %}