movie_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
# from movie_app_api import views
from movie_project import settings
from django.contrib.sitemaps.views import sitemap
from movie_app.sitemaps import MovieSitemap
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView # new


# from rest_framework import routers


admin.site.index_title = "Админ панель Django"

sitemaps = {
    "movies": MovieSitemap,
}

# router = routers.SimpleRouter()
# router.register(r'', views.MovieViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie_app.urls", namespace="index")),
    path("video/", include("video_player.urls", namespace="video_player")),
    path("user/", include("user.urls", namespace="user")),
    # debug
    path("__debug__/", include("debug_toolbar.urls")),
    # social auth
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    # sitemap
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
    # авторизация по токенам JWT
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
    # авторизация по токенам
    path("api/v1/drf-auth", include("rest_framework.urls")),
    path("api/v1/auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
    # API версия 1
    path("api/v1/", include("movie_app_api.urls")),
    # schema
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    #router
    # path("api/v1/", include(router.urls)), # for router
    # path("api/v2/", include("movie_app_api_v2.urls")), # API версия 2
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
]

video_player/urls.py
from django.urls import path
from . import views

app_name = "video_player"

urlpatterns = [
    path('film/<slug:slug_film>/watch/', views.film_player, name='film_player'),
    path('stream/film/<slug:slug_film>/<str:quality>/', views.stream_video, name='stream_video'),
    path('serial/<slug:slug_serial>/season/<int:season_number>/episode/<int:episode_number>/watch/', views.episode_player, name='episode_player'),
    path('stream/serial/<slug:slug_serial>/season/<int:season_number>/episode/<int:episode_number>/<str:quality>/', views.stream_serial, name='stream_serial'),
]

video_player/models.py
from django.db import models

# Create your models here.

video_player/views.py
from django.shortcuts import get_object_or_404, render
from movie_app.models import Movie, Serial, Episode
from django.http import StreamingHttpResponse
from .utils import open_file

def film_player(request, slug_film):
    film = get_object_or_404(Movie, slug=slug_film)
    data = {"film": film}
    return render(request, "video_player/film_player.html", context=data)

def episode_player(request, slug_serial, season_number, episode_number):
    serial = get_object_or_404(Serial, slug=slug_serial)
    episode = get_object_or_404(Episode, serial=serial, season_number=season_number, episode_number=episode_number)
    data = {
        "serial": serial,
        "episode": episode
    }
    return render(request, "video_player/episode_player.html", context=data)

def stream_video(request, slug_film, quality):
    file, status_code, content_length, content_range = open_file(request, slug_film, quality)
    response = StreamingHttpResponse(file, status=status_code)
    response['Accept-Ranges'] = 'bytes'
    response['Content-Length'] = str(content_length)
    response['Content-Type'] = 'video/mp4'
    if content_range:
        response['Content-Range'] = content_range
    return response

def stream_serial(request, slug_serial, season_number, episode_number, quality):
    episode = get_object_or_404(Episode, serial__slug=slug_serial, season_number=season_number, episode_number=episode_number)
    file, status_code, content_length, content_range = open_file(request, episode.slug, quality)
    response = StreamingHttpResponse(file, status=status_code)
    response['Accept-Ranges'] = 'bytes' 
    response['Content-Length'] = str(content_length)
    response['Content-Type'] = 'video/mp4'
    if content_range:
        response['Content-Range'] = content_range
    return response

video_player/templates/video_player/episode_player.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>{{ episode.name }} - {{ episode.serial.name }} - Movie Flow</title>
{% endblock %}

{% block css %}
<link href="https://vjs.zencdn.net/7.14.3/video-js.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/video_player.css' %}">
<link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/panel/panel.css' %}">
{% endblock %}

{% block content %}
{% include "includes/panel.html" %}
<div class="video-container">
    <video id="episode-video" class="video-js vjs-default-skin" controls preload="auto" width="100%" height="600px">
        {% for label in episode.get_video_sources %}
            <source src="{% url "video_player:stream_serial" episode.serial.slug episode.season_number episode.episode_number 480 %}" type="video/mp4" label="{{ label }}" res="{{ label }}">
        {% endfor %}
        Your browser does not support the video tag.
    </video>
    <div class="quality-menu">
        <button class="quality-button"><i class="fa fa-cog"></i> Quality</button>
        <div class="quality-options">
            {% if episode.video_medium %}
                <a href="#" data-quality="{% url 'video_player:stream_serial' episode.serial.slug episode.season_number episode.episode_number '480p' %}">480p</a>
            {% endif %}
            {% if episode.video_high %}
                <a href="#" data-quality="{% url 'video_player:stream_serial' episode.serial.slug episode.season_number episode.episode_number '720p' %}">720p</a>
            {% endif %}
            {% if episode.video_hd %}
                <a href="#" data-quality="{% url 'video_player:stream_serial' episode.serial.slug episode.season_number episode.episode_number '1080p' %}">1080p</a>
            {% endif %}
        </div>
    </div>
</div>
{% include "includes/footer.html" %}
{% endblock %}

{% block javascript %}
<script src="https://vjs.zencdn.net/7.14.3/video.min.js"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var player = videojs('episode-video');
        var qualityButton = document.querySelector('.quality-button');
        var qualityMenu = document.querySelector('.quality-menu');
        var qualityOptions = document.querySelectorAll('.quality-options a');

        qualityButton.addEventListener('click', function() {
            qualityMenu.classList.toggle('show');
        });

        qualityOptions.forEach(function(option) {
            option.addEventListener('click', function(event) {
                event.preventDefault();
                var selectedQuality = this.getAttribute('data-quality');
                var currentTime = player.currentTime();

                player.src({ type: 'video/mp4', src: selectedQuality });
                player.play().then(() => {
                    player.currentTime(currentTime);
                });

                qualityMenu.classList.remove('show');
            });
        });

        document.addEventListener('click', function(event) {
            if (!qualityMenu.contains(event.target)) {
                qualityMenu.classList.remove('show');
            }
        });

        document.addEventListener('keydown', function(event) {
            if (event.key === 'ArrowRight') {
                player.currentTime(player.currentTime() + 10);
            } else if (event.key === 'ArrowLeft') {
                player.currentTime(player.currentTime() - 10);
            } else if (event.key === 'а' || event.key === 'А' || event.key === 'F' || event.key === 'f') {
                if (player.isFullscreen()) {
                    player.exitFullscreen();
                } else {
                    player.requestFullscreen();
                }
            } else if (event.key === ' ' || event.key === 'Spacebar') {
                event.preventDefault();
                if (player.paused()) {
                    player.play();
                } else {
                    player.pause();
                }
            }
        });
    });
</script>
{% endblock %}

video_player/templates/video_player/film_player.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>{{ film.name }} - Movie Flow</title>
{% endblock %}

{% block css %}
<link href="https://vjs.zencdn.net/7.14.3/video-js.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/video_player.css' %}">
<link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/panel/panel.css' %}">
{% endblock %}

{% block content %}
{% include "includes/panel.html" %}
<div class="video-container">
    <video id="movie-video" class="video-js vjs-default-skin" controls preload="auto" width="100%" height="600px">
        {% for label in film.get_video_sources %}
            <source src="{% url "video_player:stream_video" film.slug 480 %}" type="video/mp4" label="{{ label }}" res="{{ label }}">
        {% endfor %}
        Your browser does not support the video tag.
    </video>
    <div class="quality-menu">
        <button class="quality-button"><i class="fa fa-cog"></i> Quality</button>
        <div class="quality-options">
            {% if film.video_medium %}
                <a href="#" data-quality="{% url "video_player:stream_video" film.slug '480p' %}">480p</a>
            {% endif %}
            {% if film.video_high %}
                <a href="#" data-quality="{% url "video_player:stream_video" film.slug '720p' %}">720p</a>
            {% endif %}
            {% if film.video_hd %}
                <a href="#" data-quality="{% url "video_player:stream_video" film.slug '1080p' %}">1080p</a>
            {% endif %}
        </div>
    </div>
</div>
{% include "includes/footer.html" %}
{% endblock %}

{% block javascript %}
<script src="https://vjs.zencdn.net/7.14.3/video.min.js"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script> <!-- Подключаем FontAwesome -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var player = videojs('movie-video');
        var qualityButton = document.querySelector('.quality-button');
        var qualityMenu = document.querySelector('.quality-menu');
        var qualityOptions = document.querySelectorAll('.quality-options a');

        qualityButton.addEventListener('click', function() {
            qualityMenu.classList.toggle('show');
        });

        qualityOptions.forEach(function(option) {
            option.addEventListener('click', function(event) {
                event.preventDefault();
                var selectedQuality = this.getAttribute('data-quality');
                var currentTime = player.currentTime();

                player.src({ type: 'video/mp4', src: selectedQuality });
                player.play().then(() => {
                    player.currentTime(currentTime);
                });

                qualityMenu.classList.remove('show');
            });
        });

        // Закрыть меню при клике вне его
        document.addEventListener('click', function(event) {
            if (!qualityMenu.contains(event.target)) {
                qualityMenu.classList.remove('show');
            }
        });

        // Добавляем обработчик событий для перемотки при нажатии стрелок на клавиатуре
        document.addEventListener('keydown', function(event) {
            if (event.key === 'ArrowRight') {
                player.currentTime(player.currentTime() + 10); // Перемотка вперед на 10 секунд
            } else if (event.key === 'ArrowLeft') {
                player.currentTime(player.currentTime() - 10); // Перемотка назад на 10 секунд
            } else if (event.key === 'а' || event.key === 'А' || event.key === 'F' || event.key === 'f') {
                if (player.isFullscreen()) {
                    player.exitFullscreen();
                } else {
                    player.requestFullscreen();
                }
            }  else if (event.key === ' ' || event.key === 'Spacebar') {
                event.preventDefault(); // Предотвращаем прокрутку страницы
                if (player.paused()) {
                    player.play();
                } else {
                    player.pause();
                }
            }
        });
    });
</script>
{% endblock %}