movie_app/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('movies/', views.show_all_movie, name='movies'),
    path('movie/<slug:slug_movie>/', views.show_one_movie, name='movie-detail'),
    path('serials/', views.show_all_serial, name='serials'),
    path('serial/<slug:slug_serial>/', views.show_one_serial, name='serial-detail'),
    path('actors/', views.show_actors, name='all_actors'),
    path('actor/<slug:slug_name>/', views.show_actor, name='actor_film'),
    ]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
# from movie_app_api import views
from movie_project import settings
from django.contrib.sitemaps.views import sitemap
from movie_app.sitemaps import MovieSitemap
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView # new


# from rest_framework import routers


admin.site.index_title = "Админ панель Django"

sitemaps = {
    "movies": MovieSitemap,
}

# router = routers.SimpleRouter()
# router.register(r'', views.MovieViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie_app.urls", namespace="index")),
    path("video/", include("video_player.urls", namespace="video_player")),
    path("user/", include("user.urls", namespace="user")),
    # debug
    path("__debug__/", include("debug_toolbar.urls")),
    # social auth
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    # sitemap
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
    # авторизация по токенам JWT
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
    # авторизация по токенам
    path("api/v1/drf-auth", include("rest_framework.urls")),
    path("api/v1/auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
    # API версия 1
    path("api/v1/", include("movie_app_api.urls")),
    # schema
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    #router
    # path("api/v1/", include(router.urls)), # for router
    # path("api/v2/", include("movie_app_api_v2.urls")), # API версия 2
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
]

templates/includes/footer.html
{% load static %}

<footer class="footer">
    <div class="footer-container">
        <div class="footer-logo">
            <img src="{% static 'images/movie.png' %}" alt="Logo">
            <p>Фильмы, сериалы и мультфильмы</p>
            <p>Просматривая материалы, находящиеся на данном сайте, Вы обязуетесь выполнять условия пользовательского соглашения</p>
            <p>Все права защищены, материалы предоставляются только для ознакомления</p>
            <p>© 2024-2024 Movie Flow 18+</p>
            {% comment %} <div class="social-icons"> {% endcomment %}
                {% comment %} <a href="#"><img src="{% static 'images/vk_icon.png' %}" alt="VK"></a>
                <a href="#"><img src="{% static 'images/telegram_icon.png' %}" alt="Telegram"></a> {% endcomment %}
            {% comment %} </div> {% endcomment %}
        </div>
        <div class="footer-links">
            <div class="footer-column">
                <h3>Movie Flow</h3>
                <ul>
                    <li><a href="#">Подписка Movie Flow+</a></li>
                    <li><a href="#">Заказать контент</a></li>
                    <li><a href="#">О проекте</a></li>
                    <li><a href="#">Поддержать проект</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Помощь</h3>
                <ul>
                    <li><a href="#">Вопросы и ответы (FAQ)</a></li>
                    <li><a href="#">Служба поддержки</a></li>
                    <li><a href="#">Чат Вконтакте</a></li>
                    <li><a href="#">Чат Telegram</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Другое</h3>
                <ul>
                    <li><a href="#">Заявка на удаление контента</a></li>
                    <li><a href="#">Правообладателям</a></li>
                    <li><a href="#">Пользовательское соглашение</a></li>
                    <li><a href="#">Политика конфиденциальности</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/includes/panel.html
{% load static %}

<div class="header">
    <h1><a href="{% url 'index:index' %}" class="header-link">Movie Flow</a></h1>
    <nav>
        <a href="{% url "index:movies" %}">Фильмы</a>
        <a href="{% url "index:serials" %}">Сериалы</a>
    </nav>
    <form action="{% url "index:search" %}" method="get" class="search-form">
        <div class="search-container">
            <input type="text" name="q" class="search-input" placeholder="Search movie..." required>
            <button type="submit" class="search-icon-button">
                <img src="{% static 'images/png/search_icon.png' %}" alt="Search" class="search-icon">
            </button>
        </div>
    </form>
    <div class="profile-icon">
        {% if user.is_authenticated %}
            <a href="{% url 'user:profile' %}">
                {% if user.image %}
                    <img src="{{ user.image.url }}" alt="Аватар пользователя">
                {% else %}
                    <img src="{% static 'images/profile_icon.jpeg' %}" alt="Profile">
                {% endif %}
            </a>
        {% else %}
            <a href="{% url 'user:login' %}">
                <img src="{% static 'images/profile_icon.jpeg' %}" alt="Profile">
            </a>
        {% endif %}
    </div>    
</div>