movie_app/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('movies/', views.show_all_movie, name='movies'),
    path('movie/<slug:slug_movie>/', views.show_one_movie, name='movie-detail'),
    path('serials/', views.show_all_serial, name='serials'),
    path('serial/<slug:slug_serial>/', views.show_one_serial, name='serial-detail'),
    path('actors/', views.show_actors, name='all_actors'),
    path('actor/<slug:slug_name>/', views.show_actor, name='actor_film'),
    ]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
# from movie_app_api import views
from movie_project import settings
from django.contrib.sitemaps.views import sitemap
from movie_app.sitemaps import MovieSitemap
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView # new


# from rest_framework import routers


admin.site.index_title = "Админ панель Django"

sitemaps = {
    "movies": MovieSitemap,
}

# router = routers.SimpleRouter()
# router.register(r'', views.MovieViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie_app.urls", namespace="index")),
    path("video/", include("video_player.urls", namespace="video_player")),
    path("user/", include("user.urls", namespace="user")),
    # debug
    path("__debug__/", include("debug_toolbar.urls")),
    # social auth
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    # sitemap
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
    # авторизация по токенам JWT
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
    # авторизация по токенам
    path("api/v1/drf-auth", include("rest_framework.urls")),
    path("api/v1/auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
    # API версия 1
    path("api/v1/", include("movie_app_api.urls")),
    # schema
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    #router
    # path("api/v1/", include(router.urls)), # for router
    # path("api/v2/", include("movie_app_api_v2.urls")), # API версия 2
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to="user_image", blank=True, null=True, verbose_name='Аватар')
    username = models.CharField(unique=True, max_length=150, verbose_name="Имя")

    class Meta:
        db_table = "user"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

user/forms.py
# from django_recaptcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from user.models import User


class UserLoginForm(AuthenticationForm):

    # recaptcha = ReCaptchaField()

    class Meta:
        model = User
        fields = ["username", "password", "rememder_me"]

    username = forms.CharField()
    password = forms.CharField()
    
    remember_me = forms.BooleanField(required=False)

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["username", "image", "email"]

    image = forms.ImageField(required=False)
    username = forms.CharField()
    email = forms.EmailField()

user/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from user.forms import ProfileForm, UserLoginForm, UserRegistrationForm
from django.http import HttpResponseRedirect


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():

            remember_me = form.cleaned_data.get("remember_me")
            username = request.POST["username"]
            password = request.POST["password"]

            user = auth.authenticate(username=username, password=password)
            if user:
                backend = (
                    user.backend
                    if hasattr(user, "backend")
                    else "django.contrib.auth.backends.ModelBackend"
                )
                auth.login(request, user, backend=backend)
                if remember_me:
                    request.session.set_expiry(1209600)  # 2 недели
                else:
                    request.session.set_expiry(
                        0
                    )  # Закрыть сессию при закрытии браузера

                return HttpResponseRedirect(reverse("index:index"))
    else:
        form = UserLoginForm()

    context = {"form": form}
    return render(request, "user/login.html", context)


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            backend = (
                    user.backend
                    if hasattr(user, "backend")
                    else "django.contrib.auth.backends.ModelBackend"
                )
            auth.login(request, user, backend=backend)
            return HttpResponseRedirect(reverse("index:index"))
    else:
        form = UserRegistrationForm()

    context = {"form": form}
    return render(request, "user/registration.html", context)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("index:index"))


@login_required
def profile(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("user:profile"))
    else:
        form = ProfileForm(instance=request.user)

    context = {"form": form}
    return render(request, "user/profile.html", context)

user/templates/user/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Вход в аккаунт</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<body>
    <div class="blur-background"></div>
    <a href="{% url "index:index" %}">
        <div class="title">Movie Flow</div>
    </a>
    <div class="form-container">
        <div class="toggle-buttons">
            <a href="{% url "user:login" %}">Вход</a>
            <a href="{% url "user:registration" %}">Регистрация</a>
        </div>
        <form id="login-form" class="active" method="post">
            {% csrf_token %}
            <div>
                <label for="id_username">Имя пользователя:</label>
                <input type="text" id="id_username" name="username" required>
                {% if form.username.errors %}
                    <ul class="errorlist">{{ form.username.errors }}</ul>
                {% endif %}
            </div>
            <div>
                <label for="id_password">Пароль:</label>
                <input type="password" id="id_password" name="password" required>
                {% if form.password.errors %}
                <ul class="errorlist">{{ form.password.errors }}</ul>
                {% endif %}
            </div>
            <div>
                <input type="checkbox" id="id_remember_me" name="remember_me">
                <label for="id_remember_me">Запомнить меня</label>
                {% if form.remember_me.errors %}
                <ul class="errorlist">{{ form.remember_me.errors }}</ul>
                {% endif %}
            </div>
            <button type="submit">Войти</button>
        </form>
        <div class="social-login">
            <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'images/icons8-google-48.png' %}" alt="Google"></a>
            <a href="{% url 'social:begin' 'vk-oauth2' %}"><img src="{% static 'images/icons8-vk-48.png' %}" alt="Vk"></a>
            <a href="{% url 'social:begin' 'github' %}"><img src="{% static 'images/icons8-github-50.png' %}" alt="Github"></a>
        </div>
    </div>
</body>
{% endblock %}

user/templates/user/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Настройка профиля</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/panel/panel.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}
<body>
    {% include "includes/panel.html" %}
    <h1>Настройка профиля</h1>
    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div>
            <label for="id_username">Логин:</label>
            {{ form.username.errors }}
            <input type="text" id="id_username" name="username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required>
        </div>
        <div>
            <label for="id_email">Email:</label>
            {{ form.email.errors }}
            <input type="email" id="id_email" name="email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required>
        </div>
        <div>
            {{ form.image.errors }}
            <input type="file" name="image">
        </div>
        <button type="submit">Сохранить изменения</button>
    </form>
    <h2>Безопасность</h2>
    <form method="post" class="form">
        {% csrf_token %}
        <div>
            <label for="current_password">Текущий пароль:</label>
            <input type="password" id="id_current_password" name="current_password" required>
        </div>
        <div>
            <label for="new_password">Новый пароль:</label>
            <input type="password" id="idnew_password" name="new_password" required>
        </div>
        <div>
            <label for="confirm_password">Подтверждение нового пароля:</label>
            <input type="password" id="id_confirm_password" name="confirm_password" required>
        </div>
        <button type="submit">Изменить пароль</button>
    </form>
    <a class="logout" href="{% url "user:logout" %}">Выйти</a>
    {% include "includes/footer.html" %}
</body>
{% endblock %}

user/templates/user/registration.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Регистрация</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}

{% block content %}
<body>
    <div class="blur-background"></div>
    <a href="{% url "index:index" %}">
        <div class="title">Movie Flow</div>
    </a>
    <div class="form-container">
        <div class="toggle-buttons">
            <a href="{% url "user:login" %}">Вход</a>
            <a href="{% url "user:registration" %}">Регистрация</a>
        </div>
        <form method="post" class="active" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="id_username">Логин:</label>
                <input type="text" id="id_username" name="username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required>
                {% if form.username.errors %}
                    <ul class="errorlist">{{ form.username.errors }}</ul>
                {% endif %}
            </div>
            <div>
                <label for="id_email">Email:</label>
                <input type="email" id="id_email" name="email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required>
                {% if form.email.errors %}
                    <ul class="errorlist">{{ form.email.errors }}</ul>
                {% endif %}
            </div>
            <div>
                <label for="id_password1">Пароль:</label>
                <input type="password" id="id_password1" name="password1" required>
                {% if form.password1.errors %}
                    <ul class="errorlist">{{ form.password1.errors }}</ul>
                {% endif %}
            </div>
            <div>
                <label for="id_password2">Подтверждение пароля:</label>
                <input type="password" id="id_password2" name="password2" required>
                {% if form.password2.errors %}
                    <ul class="errorlist">{{ form.password2.errors }}</ul>
                {% endif %}
            </div>
            <button type="submit">Регистрация</button>
        </form>
        <div class="social-login">
            <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'images/icons8-google-48.png' %}" alt="Google"></a>
            <a href="{% url 'social:begin' 'vk-oauth2' %}"><img src="{% static 'images/icons8-vk-48.png' %}" alt="Vk"></a>
            <a href="{% url 'social:begin' 'github' %}"><img src="{% static 'images/icons8-github-50.png' %}" alt="Github"></a>
        </div>
    </div>
</body>
{% endblock %}